// -------------------------------------------------------------------
// Generated by 365admin-publish 
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: Get SAS URL
---
*/
package cmds
import (
"context"
"encoding/json"
"os"
"path"
"github.com/nats-io/nats.go"
"github.com/nats-io/nats.go/micro"
"github.com/spf13/cobra"
"github.com/365admin/nexiintra-profile/schemas"
"github.com/365admin/nexiintra-profile/execution"
"github.com/365admin/nexiintra-profile/utils"
)
func PublishdomainsGeturlPost(ctx context.Context, args  []string)  ( *string, error) {

_, pwsherr := execution.ExecutePowerShell("john","*","nexiintra-profile","41-publish-domains","20-getsasurl.ps1","" )
if (pwsherr != nil) {
	return nil,pwsherr
}
return nil, nil
	
// end result mapping

func init(){
	
}
}
