// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Create Kubernetes Deployment
---
*/
package cmds

import (
	"context"
	"os"
	"path"

	"github.com/365admin/nexiintra-profile/execution"
	"github.com/365admin/nexiintra-profile/utils"
)

func DeploywebCreatePost(ctx context.Context, body []byte, args []string) (*string, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("nexiintra-profile"), "web.yaml"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexiintra-profile", "60-deploy-web", "50-create.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}
	return nil, nil

}
