// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Read Whitelisted Guest Domains
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/365admin/nexiintra-profile/execution"
	"github.com/365admin/nexiintra-profile/schemas"
	"github.com/365admin/nexiintra-profile/utils"
)

func ReadWhilelisteddomainsPost(ctx context.Context, args []string) (*schemas.Whilelisteddomains, error) {

	_, pwsherr := execution.ExecutePowerShell("john", "*", "nexiintra-profile", "20-read", "14-readguestdomains.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("nexiintra-profile"), "whilelisteddomains.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.Whilelisteddomains{}
	err = json.Unmarshal(data, &resultObject)
	return &resultObject, nil

}
