// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Create Kubernetes Deployment
---
*/
package endpoints

import (
	"log"

	"github.com/swaggest/usecase"
)

func DeploywebCreatePost() usecase.Interactor {
	log.Fatal("Not implemented")

	return nil
}
