// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Read Units
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/nexiintra-profile/execution"
	"github.com/365admin/nexiintra-profile/schemas"
	"github.com/365admin/nexiintra-profile/utils"
)

func ReadUnitsPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.Units) error {

		_, err := execution.ExecutePowerShell("john", "*", "nexiintra-profile", "20-read", "13-readunits.ps1", "")
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("nexiintra-profile"), "units.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.Units{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Read Units")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("20-read")
	return u
}
